client_config_backend: settings
client_config:
  client_id: 557230115604-38i9nh0k2d67k5d7dc53gmfv4049ukhb.apps.googleusercontent.com
  client_secret: kQOQd7EvLNFVW1xl49dHKlme

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive